POST http://localhost:8001/api/entries/1/documents
Content-Type: multipart/form-data; boundary=boundary
Authorization: Bearer 0i5ToOgepyWnqTnbLplWJL7rLI95ifbEE0fTc16IjxqwhhXHFe4p8UtfhIg1HQPOcGwOHN0ObeGwnXeo

--boundary
Content-Disposition: form-data; name="document"; filename="sample.jpg"

< /mnt/c/Users/Markus/Downloads/sample.jpg
